### ISSUE TITLE
Server folder not recognized on already running server.

### ISSUE THREAD

**Issue by wbatzle** [Robomikel/Steam-Server-Manager#100]
I have an issue where I built a server using SteamCMD and put it in the root before I found this app. It keeps saying the folder does not exist do you want to create it. The folder below is where the server resides. Am I doing something wrong?
C:\SteamCMD\7dtd

**Comment by Robomikel** [comment]
check this [Wiki](https://github.com/Robomikel/Steam-Server-Manager/wiki/Custom-Backup-and-ServerFiles-Directories) and let me know if it helps. You can use custom server paths with ssm, default it creates its own in the root of the install. also, since you are using a custom folder name, you just need to provide the app id. 
1. Use  `./ssm` command (no params) to make sure it builds a local_settings.ps1. in `config-local` folder
2. Change local_settings.ps1 to the path of `C:\SteamCMD` for serverfiles
3. `./ssm install 7dtd` from where ever you are running the script OR you can add to [path](https://github.com/Robomikel/Steam-Server-Manager/wiki/Installing-SSM-to-PATH) of powershell.
4. provide app id `294420` when it see's a custom folder name for the serverfiles.
5.  verify it builds a Variables_*.ps1 in your serverfiles root.

**Comment by Robomikel** [comment]
Here is the folder structure. I will make sure to add this to the Wiki. you brought up a good point. this makes it a bit easier to grasp the first time. 
https://github.com/Robomikel/Steam-Server-Manager/wiki/ssm-folder-structure
